### ISSUE TITLE
Enzyme unit tests are failing in CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Codecademy/component-test-setup#2]
I missed this in #1...

```
  ● setupEnzyme › uses a default prop value when not overridden

    TypeError: Cannot read property 'child' of undefined

      32 |       ...testProps,
      33 |     } as React.ComponentProps<ComponentType>;
    > 34 |     const wrapper = mount(<Component {...(props as any)} />);
         |                     ^
      35 | 
      36 |     return { props, wrapper };
      37 |   };

      at getFiber (node_modules/enzyme-adapter-react-16/src/detectFiberTags.js:15:35)
      at detectFiberTags (node_modules/enzyme-adapter-react-16/src/detectFiberTags.js:76:15)
      at ReactSixteenAdapter.createMountRenderer (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:465:19)
      at ReactSixteenAdapter.createRenderer (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:820:51)
      at new ReactWrapper (node_modules/enzyme/src/ReactWrapper.js:113:32)
      at mount (node_modules/enzyme/src/mount.js:10:10)
      at renderWrapper (src/setupEnzyme.tsx:34:21)
      at Object.<anonymous> (src/setupEnzyme.test.tsx:18:25)
```

**Comment by wesleyduff** [comment]
So what was the issue?
